showcase/landPage/urls.py
from django.urls import path
from . import views

app_name="landPage"
urlpatterns = [
    path("", views.index, name='index'),
    path("resume", views.resume, name='resume'),
]

showcase/polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    ]

showcase/post/urls.py
from django.urls import path

from . import views


app_name = 'post'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('<int:post_id>/reply', views.reply, name='reply'),
    path('<int:post_id>/likes/', views.likes, name='likes'),
]

showcase/showcase/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('landPage.urls')),
    path('post/', include('post.urls', namespace="post")),
    path('polls/', include('polls.urls')),
    path('theodinproject/', include('theodinproject.urls', namespace="theodinproject")),
    path('admin/', admin.site.urls),
    path('cssAnimations/', include('cssAnimations.urls', namespace='cssAnimations')),
]

showcase/theodinproject/urls.py
from django.urls import path

from . import views

app_name='theodinproject'
urlpatterns = [
    path('', views.index, name='index'),
    path('fizzbizz', views.fizzbizz, name='fizzbizz'),
    path('rockpaperscissors', views.rockpaperscissors, name='rockpaperscissors'),
    path('DOM', views.DOM, name='DOM'),
    path('javascript30', views.javascript30, name='javascript30'),
    path('keyboardDrumKit', views.keyboardDrumKit, name='keyboardDrumKit'),
    path('etchASketch', views.etchASketch, name='etchASketch'),
    path('calculator', views.calculator, name='calculator'),
    path('library', views.library, name='library'),
    path('tic-tac-toe', views.ticTacToe, name='tic-tac-toe'),
    path('newLibrary', views.newLibrary, name='newLibrary'),
]

showcase/theodinproject/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.template import loader

def index(request):
    template = loader.get_template('theodinproject/index.html')
    return render(request, 'theodinproject/index.html')

def fizzbizz(request):
    template = loader.get_template('theodinproject/fizzbizz.html')
    return render(request, 'theodinproject/fizzbizz.html')

def rockpaperscissors(request):
    template = loader.get_template('theodinproject/rockpaperscissors.html')
    return render(request, 'theodinproject/rockpaperscissors.html')

def DOM(request):
    template = loader.get_template('theodinproject/DOM.html')
    return render(request, 'theodinproject/DOM.html')

def javascript30(request):
    template = loader.get_template('theodinproject/javascript30/javascript30.html')
    return render(request, 'theodinproject/javascript30/javascript30.html')

def keyboardDrumKit(request):
    template = loader.get_template('theodinproject/javascript30/keyboardDrumKit/keyboardDrumKit.html')
    return render(request, 'theodinproject/javascript30/keyboardDrumKit/keyboardDrumKit.html')

def etchASketch (request):
    template = loader.get_template('theodinproject/etchASketch.html')
    return render(request, 'theodinproject/etchASketch.html')

def calculator (request):
    template = loader.get_template('theodinproject/calculator.html')
    return render(request, 'theodinproject/calculator.html')

def library (request):
    template = loader.get_template('theodinproject/odin-projects/library.html')
    return render(request, 'theodinproject/odin-projects/library.html')

def ticTacToe (request):
    template = loader.get_template('theodinproject/odin-projects/tic-tac-toe.html')
    return render(request, 'theodinproject/odin-projects/tic-tac-toe.html')

def newLibrary(request):
    template = loader.get_template('theodinproject/odin-projects/newLibrary.html')
    return render(request, 'theodinproject/odin-projects/newLibrary.html')

"""
def script(request):
    template = loader.get_template('')
    return render(request, '')
"""

showcase/theodinproject/templates/theodinproject/DOM.html
<!DOCTYPE html>

<html>
  <head>
    <title>Document Object Manipulation (DOM)</title>
    {% load static %}
  </head>

  <!--
    1. a <p> with red text that says “Hey I’m red!”
    2. an <h3> with blue text that says “I’m a blue h3!”
    3. a <div> with a black border and pink background color with the following elements inside of it:
        another <h1> that says “I’m in a div”
        a <p> that says “ME TOO!”
        Hint for this one: after creating the div with createElement, append the <h1> and <p> to it before adding it to the container.
    -->
  <body>

      <div id="container"></div>

      <script src="{% static 'DOM/DOM.js' %}">




      </script>


  </body>
</html>

showcase/theodinproject/templates/theodinproject/calculator.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Calculator | EvanPatrick.net</title>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link type="text/css" rel="stylesheet" href="{% static 'calculator/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet" />
  </head>
  <body>
    <div id="header">
      <h1>Basic Calculator</h1>
    </div>
    <div class="btn">
      <p1> Trig functions do not yet work</p1>
    </div>
    <div class="calculator">
      <div class="screen" data-screen>0</div>
      <div class="buttons-grid">
        <div id='numbers'>
          <div class="row" id="row-6">
            <div class="btn" data-operator>x!</div>
            <div class="btn" data-operator>x^y</div>
            <div class="btn" id="">?</div>
          </div>
          <div class="row" id="row-5">
            <div class="btn" id="">tan(x)</div>
            <div class="btn" id="">sin(x)</div>
            <div class="btn" id="">cos(x)</div>
          </div>
          <div id='row-4' class='row'>
            <button class="btn" data-number>7</button>
            <button class="btn" data-number>8</button>
            <button class="btn" data-number>9</button>
          </div>
          <div id='row-3' class='row'>
            <button class="btn" data-number>4</button>
            <button class="btn" data-number>5</button>
            <button class="btn" data-number>6</button>
          </div>
          <div id='row-2' class='row'>
            <button class="btn" data-number>1</button>
            <button class="btn" data-number>2</button>
            <button class="btn" data-number>3</button>
          </div>
          <div id='row-1' class='row'>
            <button class="btn" data-point>.</button>
            <button class="btn" data-number>0</button>
            <button class="btn" data-equals>=</button>
          </div>
        </div>
        <div id='operand-buttons'>
          <button class="o-btn" data-operator>÷</button>
          <button class="o-btn" data-operator>×</button>
          <button class="o-btn" data-operator>−</button>
          <button class="o-btn" data-operator>+</button>
          <button class="o-btn btn-red span-2" data-clear>CLEAR</button>
          <button class="o-btn btn-blue span-2" data-delete>DELETE</button>
        </div>
      </div>
    <script src="{% static 'calculator/calculator.js' %}"></script>
  </body>
</html>

showcase/theodinproject/templates/theodinproject/etchASketch.html
<!DOCTYPE html>
<html>

<head>
  <title></title>
  {% load static %}
  <link type="text/css" rel="stylesheet" href="{% static 'etchasketch/style.css' %}">
</head>





<body>
<div id="title">
  <h1>Pixel-Pad</h1>
</div>

<div id="content-holder">
  <div id="button-holder">
    <button id="eraser-btn">Toggle Eraser</button>
    <button id="erase-all">Erase All</button>
    <div id="color-card">
      <div id="color-box">
        <input type="color" id="color-select">
      </div>
      <span>Pick your color</span>
    </div>

    <div class="slider-box">
        <input type="range" value="48" min="1" max="60" id="range-slider"
        onChange="rangeSlider(this.value)">
        <div id="progress-bar"></div>

        <p class="grid-size">Grid size: <span id="range-value">48</span> x <span id="range-value">48</span></p>
    </div>
  </div>
  <div id="board-holder">
    <div id="board" draggable="false"></div>
  </div>
</div>

<script src="{% static 'etchasketch/etchasketch.js' %}"></script>
</body>

</html>

showcase/theodinproject/templates/theodinproject/fizzbizz.html
<!DOCTYPE html>

  <html>
    <head>
      {% load static %}
      <link type="text/css" rel="stylesheet" href="{% static 'fizzbuzz/style.css' %}">
    </head>



    <body>

      <p>This is the FizzBuzz game. Whenever something is divisible by 3 it outputs Fizz, whenever it is divisible by 5 it outputs Buzz, Whenever it is divisible by both it outputs FizzBuzz.</p>

      <div id=output></div>
      <script src="{% static 'fizzbuzz/fizzbuzz.js' %}">




      </script>

    </body>

  </html>

showcase/theodinproject/templates/theodinproject/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>The Odin Project Page</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'theodinproject/style.css' %}">
  </head>

  <body>

    <div id="view">
      <div id="header">
        <h1>The Odin Project Page</h1>
      </div>

      <div id="nav-bar">
        <a id="home" class="nav-item" href="{% url 'landPage:index' %}">Home Page</a>
        <a class="nav-item" href="{% url 'theodinproject:index' %}">The Odin Project Files</a>
        <a class="nav-item" href="{% url 'cssAnimations:index' %}">Various CSS Animations</a>
        <!--<a class="nav-item" href="{% url 'theodinproject:javascript30' %}">Javascript30</a>-->
        <a class="nav-item" href="{% url 'polls:index' %}">Voting Poll App</a>
      </div>


      <div id="main">
        <div id="text">
          <p2><a class="noticable-link" href="https://www.theodinproject.com">The Odin Project</a> is a very informative and free webdesign course that I have been slowly chugging through. And has been the biggest resource in my path of obtaining a webdesign carrer.</p>
        </div>

        <div id="main-content">
          <div class="row">
            <a class="content-item" href="{% url 'theodinproject:etchASketch' %}">Etch a Sketch</a>
            <a class="content-item" href="{% url 'theodinproject:rockpaperscissors' %}">Rock Paper Scissors Game</a>
            <a class="content-item" href="{% url 'theodinproject:fizzbizz' %}">FizzBuzz</a>
            <a class="content-item" href="{% url 'theodinproject:DOM' %}">Document Object Model</a>
          </div>
          <div class="row">
            <a class="content-item" href="{% url 'theodinproject:calculator' %}">Calculator</a>
            <a class="content-item" href="{% url 'theodinproject:library' %}">Basic Object Constructor</a>
            <a class="content-item" href="{% url 'theodinproject:tic-tac-toe' %}">tic tac toe</a>
            <a class="content-item" href="{% url 'theodinproject:library' %}">Library</a>
          </div>
          <div class="row">
            <a class="content-item" href="{% url 'theodinproject:newLibrary' %}">New Library</a>
            <a class="content-item" href="#">#</a>
            <a class="content-item" href="#">#</a>
            <a class="content-item" href="#">#</a>
          </div>
        </div>
      </div>
    </div>
  </body>



</html>

showcase/theodinproject/templates/theodinproject/rockpaperscissors.html
<!DOCTYPE html>

<html>
  <head>
    <title>Rock Paper Scissors Game | EvanPatrick.net</title>
    {% load static %}
    <link type="text/css" rel="stylesheet" href="{% static 'rockpaperscissors/style.css' %}">
  </head>

  <body>


    <div id='dashboard'>
      <div id='message'></div>
      <div id='current'></div>
      <div id='container'>
        <button class="btn" id='rock'>Rock</button>
        <button class="btn" id='paper'>Paper</button>
        <button class="btn" id='scissors'>Scissors</button>
      </div>
    </div>
    <script src="{% static 'rockpaperscissors/rockpaperscissors.js' %}">

    </script>



  </body>





</html>