showcase/landPage/urls.py
from django.urls import path
from . import views

app_name="landPage"
urlpatterns = [
    path("", views.index, name='index'),
    path("resume", views.resume, name='resume'),
]

showcase/polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    ]

showcase/post/urls.py
from django.urls import path

from . import views


app_name = 'post'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('<int:post_id>/reply', views.reply, name='reply'),
    path('<int:post_id>/likes/', views.likes, name='likes'),
]

showcase/showcase/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('landPage.urls')),
    path('post/', include('post.urls', namespace="post")),
    path('polls/', include('polls.urls')),
    path('theodinproject/', include('theodinproject.urls', namespace="theodinproject")),
    path('admin/', admin.site.urls),
    path('cssAnimations/', include('cssAnimations.urls', namespace='cssAnimations')),
]

showcase/theodinproject/urls.py
from django.urls import path

from . import views

app_name='theodinproject'
urlpatterns = [
    path('', views.index, name='index'),
    path('fizzbizz', views.fizzbizz, name='fizzbizz'),
    path('rockpaperscissors', views.rockpaperscissors, name='rockpaperscissors'),
    path('DOM', views.DOM, name='DOM'),
    path('javascript30', views.javascript30, name='javascript30'),
    path('keyboardDrumKit', views.keyboardDrumKit, name='keyboardDrumKit'),
    path('etchASketch', views.etchASketch, name='etchASketch'),
    path('calculator', views.calculator, name='calculator'),
    path('library', views.library, name='library'),
    path('tic-tac-toe', views.ticTacToe, name='tic-tac-toe'),
    path('newLibrary', views.newLibrary, name='newLibrary'),
]

showcase/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

showcase/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())



def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

showcase/polls/templates/polls/detail.html
<!DOCTYPE html>
  <html>
    <head>
      <title></title>
    </head>
    <body>

      <h1>{{ question.question_text }}</h1>
      {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

      <form action="{% url 'polls:vote' question.id %}" method="post">
      {% csrf_token %}
      {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
      {% endfor %}
      <input type="submit" value="Vote">
      </form>
    </body>
  </html>

showcase/polls/templates/polls/index.html
<!DOCTYPE html>

<html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

  <head>
    <title>Voting Poll Page</title>
  </head>

  <body>

    <div id="view">
      <div id="header">
        <h1>Voting poll app</h1>
      </div>

      <div id="nav-bar">
        <a id="home" class="nav-item" href="{% url 'landPage:index' %}">Home Page</a>
        <a class="nav-item" href="{% url 'theodinproject:index' %}">The Odin Project Files</a>
        <a class="nav-item" href="{% url 'cssAnimations:index' %}">Various CSS Animations</a>
        <!--<a class="nav-item" href="{% url 'theodinproject:javascript30' %}">Javascript30</a>-->
        <a class="nav-item" href="{% url 'polls:index' %}">Voting Poll App</a>
      </div>
    </div>

<!-- ----------------------------------------------------------------------- -->

    <div id="poll-questions">

      {% if latest_question_list %}
        <div id="poll-question-ul">
          {% for question in latest_question_list %}
            <a id ="poll-question" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
          {% endfor %}
        </div>
      {% else %}
        <p>No polls are available.</p>
      {% endif %}

    </div>

  </body>

</html>

showcase/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>