showcase/post/urls.py
from django.urls import path

from . import views


app_name = 'post'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('<int:post_id>/reply', views.reply, name='reply'),
    path('<int:post_id>/likes/', views.likes, name='likes'),
]

showcase/showcase/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('landPage.urls')),
    path('post/', include('post.urls', namespace="post")),
    path('polls/', include('polls.urls')),
    path('theodinproject/', include('theodinproject.urls', namespace="theodinproject")),
    path('admin/', admin.site.urls),
    path('cssAnimations/', include('cssAnimations.urls', namespace='cssAnimations')),
]

showcase/theodinproject/urls.py
from django.urls import path

from . import views

app_name='theodinproject'
urlpatterns = [
    path('', views.index, name='index'),
    path('fizzbizz', views.fizzbizz, name='fizzbizz'),
    path('rockpaperscissors', views.rockpaperscissors, name='rockpaperscissors'),
    path('DOM', views.DOM, name='DOM'),
    path('javascript30', views.javascript30, name='javascript30'),
    path('keyboardDrumKit', views.keyboardDrumKit, name='keyboardDrumKit'),
    path('etchASketch', views.etchASketch, name='etchASketch'),
    path('calculator', views.calculator, name='calculator'),
    path('library', views.library, name='library'),
    path('tic-tac-toe', views.ticTacToe, name='tic-tac-toe'),
    path('newLibrary', views.newLibrary, name='newLibrary'),
]

showcase/theodinproject/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.template import loader

def index(request):
    template = loader.get_template('theodinproject/index.html')
    return render(request, 'theodinproject/index.html')

def fizzbizz(request):
    template = loader.get_template('theodinproject/fizzbizz.html')
    return render(request, 'theodinproject/fizzbizz.html')

def rockpaperscissors(request):
    template = loader.get_template('theodinproject/rockpaperscissors.html')
    return render(request, 'theodinproject/rockpaperscissors.html')

def DOM(request):
    template = loader.get_template('theodinproject/DOM.html')
    return render(request, 'theodinproject/DOM.html')

def javascript30(request):
    template = loader.get_template('theodinproject/javascript30/javascript30.html')
    return render(request, 'theodinproject/javascript30/javascript30.html')

def keyboardDrumKit(request):
    template = loader.get_template('theodinproject/javascript30/keyboardDrumKit/keyboardDrumKit.html')
    return render(request, 'theodinproject/javascript30/keyboardDrumKit/keyboardDrumKit.html')

def etchASketch (request):
    template = loader.get_template('theodinproject/etchASketch.html')
    return render(request, 'theodinproject/etchASketch.html')

def calculator (request):
    template = loader.get_template('theodinproject/calculator.html')
    return render(request, 'theodinproject/calculator.html')

def library (request):
    template = loader.get_template('theodinproject/odin-projects/library.html')
    return render(request, 'theodinproject/odin-projects/library.html')

def ticTacToe (request):
    template = loader.get_template('theodinproject/odin-projects/tic-tac-toe.html')
    return render(request, 'theodinproject/odin-projects/tic-tac-toe.html')

def newLibrary(request):
    template = loader.get_template('theodinproject/odin-projects/newLibrary.html')
    return render(request, 'theodinproject/odin-projects/newLibrary.html')

"""
def script(request):
    template = loader.get_template('')
    return render(request, '')
"""

showcase/theodinproject/templates/theodinproject/javascript30/javascript30.html
<!DOCTYPE html>
<html>
  <head>
    <title>Javascript30 Page</title>
  </head>
  <body>
    <p>Javascript30 page things will go here, I want to do most of them because they are really cool</p>

    <a href="{% url 'theodinproject:keyboardDrumKit' %}">Keyboard Drum Kit</a></li>

    <script>


    </script>


  </body>


</html>

showcase/theodinproject/templates/theodinproject/javascript30/keyboardDrumMachine.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>JS Drum Kit</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>


  <div class="keys">
    <div data-key="65" class="key">
      <kbd>A</kbd>
      <span class="sound">clap</span>
    </div>
    <div data-key="83" class="key">
      <kbd>S</kbd>
      <span class="sound">hihat</span>
    </div>
    <div data-key="68" class="key">
      <kbd>D</kbd>
      <span class="sound">kick</span>
    </div>
    <div data-key="70" class="key">
      <kbd>F</kbd>
      <span class="sound">openhat</span>
    </div>
    <div data-key="71" class="key">
      <kbd>G</kbd>
      <span class="sound">boom</span>
    </div>
    <div data-key="72" class="key">
      <kbd>H</kbd>
      <span class="sound">ride</span>
    </div>
    <div data-key="74" class="key">
      <kbd>J</kbd>
      <span class="sound">snare</span>
    </div>
    <div data-key="75" class="key">
      <kbd>K</kbd>
      <span class="sound">tom</span>
    </div>
    <div data-key="76" class="key">
      <kbd>L</kbd>
      <span class="sound">tink</span>
    </div>
  </div>

  <audio data-key="65" src="sounds/clap.wav"></audio>
  <audio data-key="83" src="sounds/hihat.wav"></audio>
  <audio data-key="68" src="sounds/kick.wav"></audio>
  <audio data-key="70" src="sounds/openhat.wav"></audio>
  <audio data-key="71" src="sounds/boom.wav"></audio>
  <audio data-key="72" src="sounds/ride.wav"></audio>
  <audio data-key="74" src="sounds/snare.wav"></audio>
  <audio data-key="75" src="sounds/tom.wav"></audio>
  <audio data-key="76" src="sounds/tink.wav"></audio>

<script>

</script>


</body>
</html>