showcase/landPage/urls.py
from django.urls import path
from . import views

app_name="landPage"
urlpatterns = [
    path("", views.index, name='index'),
    path("resume", views.resume, name='resume'),
]

showcase/polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    ]

showcase/post/urls.py
from django.urls import path

from . import views


app_name = 'post'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('<int:post_id>/reply', views.reply, name='reply'),
    path('<int:post_id>/likes/', views.likes, name='likes'),
]

showcase/showcase/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('landPage.urls')),
    path('post/', include('post.urls', namespace="post")),
    path('polls/', include('polls.urls')),
    path('theodinproject/', include('theodinproject.urls', namespace="theodinproject")),
    path('admin/', admin.site.urls),
    path('cssAnimations/', include('cssAnimations.urls', namespace='cssAnimations')),
]

showcase/theodinproject/urls.py
from django.urls import path

from . import views

app_name='theodinproject'
urlpatterns = [
    path('', views.index, name='index'),
    path('fizzbizz', views.fizzbizz, name='fizzbizz'),
    path('rockpaperscissors', views.rockpaperscissors, name='rockpaperscissors'),
    path('DOM', views.DOM, name='DOM'),
    path('javascript30', views.javascript30, name='javascript30'),
    path('keyboardDrumKit', views.keyboardDrumKit, name='keyboardDrumKit'),
    path('etchASketch', views.etchASketch, name='etchASketch'),
    path('calculator', views.calculator, name='calculator'),
    path('library', views.library, name='library'),
    path('tic-tac-toe', views.ticTacToe, name='tic-tac-toe'),
    path('newLibrary', views.newLibrary, name='newLibrary'),
]

showcase/post/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.
class Post(models.Model):
    post_title = models.CharField(max_length=50)
    post_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.post_title

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Reply(models.Model):
    Post = models.ForeignKey(Post, on_delete=models.CASCADE)
    reply_text = models.CharField(max_length=1000)
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)

    def __str__(self):
        return self.reply_text

showcase/post/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Post, Reply
from django.core.exceptions import ObjectDoesNotExist


def index(request):
    latest_post_list = Post.objects.order_by('-pub_date')[:5]
    context = {'latest_post_list': latest_post_list}
    return render(request, 'post/index.html', context)

def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post/detail.html', {'post':post})

def reply(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post/results.html', {'post': post})

def likes(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    try:
        selected_reply = post.reply_set.get(pk=request.POST['reply'])
    except (KeyError, reply.DoesNotExist):
        # Redisplay the post voting form.
        return render(request, 'post/detail.html', {
        'post': post,
        'error_message': "You didn't select a response.",
        })
    else:
        selected_reply.likes +=1
        selected_reply.save()
        # Alwasy return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('post:likes', args=(post.id,)))

showcase/post/templates/post/detail.html
<!DOCTYPE html>

<head>
  <title>{{ post.post_title }}</title>
</head>

<body>

  <h1>{{ post.post_title }}</h1>

  <p1>{{ post.post_text }}</p1>

  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

  <form action="{% url 'post:likes' post.id %}" method="post">
  {% csrf_token %}
  {% for reply in post.reply_set.all %}
    <ul>
      <li>{{reply.reply_text}}</li>
    </ul>
    <input type="radio" name="likes" id="reply{{ forloop.counter }}" value="{{ reply.id }}">
    <label for="reply{{ forloop.counter }}">like?</label><br>
  {% endfor %}
  <input type="submit" value="vote">
  </form>

  <!--
  <h1>{{ post.post_title }}</h1>
  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
  <p1>{{ post.post_text }}</p1>
  <p1><br><br>Replies to this post</p1>
  <ul>
    {% if post.reply_set %}
      {% for reply in post.reply_set.all %}
        <li>{{ reply.reply_text }}</li>
        <li>Likes {{ reply.likes }}</li>
        <li>Dislikes {{ reply.dislikes }}</li>
        <br><br>
      {% endfor %}
    {% endif %}
  </ul>
  -->
</body>

showcase/post/templates/post/index.html
<!DOCTYPE html>



<head>
  <title>Blog Post Page</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'post/style.css' %}">
</head>

<body>

  <div id="view">
    <div id="header">
      <h1>Blog Post Page</h1>
    </div>

    <div id="nav-bar">
      <a id="home" class="nav-item" href="{% url 'landPage:index' %}">Home Page</a>
      <a class="nav-item" href="{% url 'theodinproject:index' %}">The Odin Project Files</a>
      <a class="nav-item" href="{% url 'cssAnimations:index' %}">Various CSS Animations</a>
      <a class="nav-item" href="{% url 'theodinproject:javascript30' %}">Javascript30</a>
      <a class="nav-item" href="{% url 'polls:index' %}">Voting Poll App</a>
    </div>

  </div>


<!-- ----------------------------------------------------------------------- -->


{% if latest_post_list %}
  <ul>
    {% for post in latest_post_list %}
      <li><a href="{% url 'post:detail' post.id %}">{{ post.post_title}}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>No posts are available.</p>
{% endif %}

</body>

showcase/post/templates/post/results.html
<!DOCTYPE html>
<html>
  <head>
    <title></title>
  </head>

  <body>

    <h1>{{ post.post_title }}</h1>

    <ul>
    {% for reply in post.reply_set.all %}
      <li>{{ reply.reply_text }} -- {{ reply.likes }} likes</li>
    {% endfor %}
    </ul>

    <a href="{% url 'post:detail' post.id %}">Vote again?</a>


  </body>

</html>